dist:
  xenial

language:
  python

python:
  - 3.7

install:
  - pip install pipenv
  - pipenv sync --dev

git:
  depth: 3

branches:       # since the master branch is the only one where PRs are
  only:         # merged in
    - master

script:
  - scripts/run_small.sh                            # tests small instances
  - scripts/validate.sh                             # verifies feasibility
  - pytest                                          # unit tests
  - mypy ./ || true                                 # static code analyser
